--- 
title: "Statistics, Models and Machine Learning"
author: "Michoel Snow"
# date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
# bibliography: [book.bib, packages.bib]
biblio-style: apalike2
link-citations: yes
output_dir: "docs"
# github-repo: rstudio/bookdown-demo
# description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---


# Introduction

Should I be using linear regression, logistics regression, SVM, neural networks or one of at least a dozen other statistical/machine learning algorithms when trying to model my data?  This is the fundamental question which has driven the authorship of this book.  The problem is that the answer to that question for the most part is always the same, it depends.  The answer depends not only on the data itself, but also why you are modeling in the first place, i.e., what question are you trying to answer with your model, as well as a whole host of other factors.  The purpose of this book is to help you identify the important factors for choosing a model,  given those factors which model(s) you should choose and why, and then finally how to implement that model in R or python.

## Motivation for this book

In undergrad I majored in bioengineering, then for grad school I started doing some basic modeling work in neuroscience. As I was only working with a few models, I really only needed to learn the inner workings of those specific models.  However, after grad school when I was interviewing for jobs, they would often follow a similar pattern.  Either I would be asked about which modeling approaches I felt comfortable with or about alternative modeling approaches for my research than the ones I used.   To say I floundered would be a kind description of my response to these questions.  It was obvious that to be competitive I needed to build a real foundation in modeling approaches.  

When I started reading books and taking courses, I ran into a different set of issues.  The vast majority of these sources were written assuming that the learner was still in midst of schooling and had only recently taken courses like statistics and linear algebra.  I had taken those courses over a decade before and my current knowledge of those fields was limited to the techniques that I was using at the time, and even for the the techniques I was still using, I had long forgotten their theoretical underpinnings.  Thus this book tries to be complete in the sense that it only assumes the most basic knowledge of statistics and a bit of linear algebra, i.e., vector and matrix multiplication. That being said, I try to approach most concepts from multiple directions so even if vector and matrix operations are not your strong suit you should still come away with at least intuitive understanding of the presented topics. 


## How to read this book 

This book is long on purpose.  I strove to make this book a one stop shop for all concepts related to the discussed topics, including multiple derivations and long winded discussions on what some might consider, simple ideas. This is intentional, and as such this book is more intended as a complete reference and I do not expect the average person to read the entire thing straight from start to finish.  I have written it so that it can be read from start to finish but I expect most people to jump around to the topics that interest them and skip those that do not.  To make this a little easier I have tried to be consistent in how material is presented.

This book is broken up by model, ordered by computational complexity.  Every chapter begins with a series of dataset visualizations and associated questions which are best answered through the models described in that chapter.  Each chapter is intended to be modular and for the most part, you can read any of the chapters in any order.  When multiple models utilize statistics or statistical techniques, the technique will be discussed the first time it is mentioned and all later mentions will refer the reader to where in the book they can find an explanation of that technique. 

## Notation and nomeclature used in this book

We are all aware of the need for precision in mathematics and computation so as not to create unintentional errors, but I feel the same is true for language, especially in the description of mathematics and computation.  For that reason I will strive to be consistent in my use of terminology, use the simplest possible accurate term and use as few terms as possible.  For the sake of those who read other books on the subject, whenever a new term is introduced I will try to give all other commonly used names for that term.   I will also bold a term whenever I give its definition.  Note that when these rules disagree with standard agreed upon nomenclature, I will defer to the standard nomenclature, but will then explicitly define the terms to avoid confusion.

Mathematical modeling lies at the heart of statistical learning, machine learning and any other name dreamt up by a marketing department.  So instead of trying to define where one field ends and the other begins, or which technique is machine learning and which is statistics I am simply going to use the term model.  In this book any relationship between variables is a **model**.  A **variable** is a symbol which contains one or more known or unknown values.  When the variable can contain any number of subset variables I will use the bold typeface and capital letters to represent it, such as $\mathbf{X}$ or $\mathbf{Y}$.  Variables which contain no subset variables will be written using the regular typeface and capital letters, such as $X$ or $Y$.  Individual values of a variable known as **observations**, also referred to as samples, will be written using a regular typeface and lowercase letters, such as $x$ or $y$.  Indvidual observations for multiple variable will be written using the bold typeface and lowercase letters, such as $\mathbf{x}$ or $\mathbf{y}$.  Numbered subscripts will refer to a specific subset or observation and lettered subscripts will be used for generic subsets or observations. When referring to both individual observations and subset variables, the first subscript is the observation and the second is the variable. The generic total number of observations is $n$ and the generic total number of variables is $p$.

THis will make more sense when put together in an example.  Let us say I am building a model which takes as its first four inputs the GPA, major, minor and high school of every student in Cornell's graduating class of 1900.  $\mathbf{X}$ refers to the set of all input variables. $X_1$ refers to the GPA of all students and $X_2$ refers to their major.  $\mathbf{x}_1$ refers to all the inputs for the first student and $\mathbf{x}_i$ refers to the set of inputs for some generic $i$th student.  $x_{3,1}$ refers to the GPA for the third student.  You can also think of this as a table where the rows are the observations and the columns are the subset variables.  In matrix format this would look like:

$$\mathbf{X} = 
\left(X_1\; X_2\; X_3\; \ldots \; X_p\right)=
\left(\begin{array} {c}
\mathbf{x}_1 \\
\mathbf{x}_2 \\
\mathbf{x}_3 \\
\vdots \\
\mathbf{x}_n
\end{array}\right) = 
\left(\begin{array}
{rrr}
x_{1,1} & x_{1,2} & x_{1,3} & \ldots & x_{1,p}\\
x_{2,1} & x_{2,2} & x_{2,3} & \ldots & x_{2,p}\\
x_{3,1} & x_{3,2} & x_{3,3} & \ldots & x_{3,p}\\
\vdots & \vdots & \vdots & \ddots & \vdots\\
x_{n,1} & x_{n,2} & x_{n,3} & \ldots & x_{n,p}\\
\end{array}\right)$$


Unlike variables which are one or more unknowns, **values** are unknowns which always only take on a single value and will be represented with a lowercase letter, e.g., $a$.  Values which are associated with variables will share their subscripts, e.g., a value, $b$, associated with variable $X_i$, will be referenced as $b_i$. A value associated with a specific variable is referred to as its **coefficient**.

A **function** is a rule for taking an input and returning an output and is represented with a lower case letter followed by a pair of parentheses surrounding the input, e.g., $f(input)$.  Variables which are part of a function's input are not suprisingly input variables, these are also referred to as indepedent variables, predictors or features.  Similarly variables in the output will be termed output variables, but are also called dependent variables or responses. Using the model of a straight line, whose equation is $$Y = mX + b$$ I can rewrite this as a function of the variable $X$ as $$ f(X) = mX + b$$ where $f(X) = Y$.

When building models often times we are only estimating the value of a coefficient or variable and don't know its actual value. To distinguish **estimates** of variables and coefficients from their true counterparts, we put tiny hats on them, e.g., $\hat{\mathbf{Y}}$, $\hat{x}_{i,j}$ or $\hat{a}_0$.



## Supervised vs Unsupervised Models

There are many ways to subdivide the various mathematical models, but for the topics covered within this book the dichotomy is made between supervised and unsupervised models.  In Supervised models the data usually consists of observations where for every observation there is a paired input and output.  In supervised modeling you are often given a training dataset which consists of entries for both the inputs and the outputs, as well as a test dataset, which only contains inputs from which you must predict outputs. The goal in supervised modeling is to create a function which accurately transforms the inputs into the outputs. In general the output only consists of a single variable but the input can consist of one or more variables.  The standard nomenclature is to use one symbol for the output and one symbol for the input.   

In unsupervised learning the data is unlabeled, i.e., it is not split into inputs and outputs and the goal is to learn some desired feature about the data.  A classic problem in unsupervised learning, is clustering, wherein the goal is to split the data into groups such that data within each group is more similar to each other than to data in other groups.

### Solving Supervised Models

In general, the goal of supervised models is to design a function which can estimate a desired output variable $\mathbf{Y}$, given a set of input variables $\mathbf{X}$, either for the puproses of predicting future outputs or for understanding the relationship between the inputs and the outputs.   All supervised models assume that there is some relationship between $\mathbf{X}$ and $\mathbf{Y}$ such that the output variable $\mathbf{Y}$ is a function of some fixed, but unknown function of $\mathbf{X}$, written as $f(\mathbf{X})$: 

\begin{equation}
  \mathbf{Y} \approx f(\mathbf{X}) 
  (\#eq:SupModApprox)
\end{equation}

In equation \@ref(eq:SupModApprox), $\mathbf{Y}$ is only approximately equal to $f(\mathbf{X})$ because there almost always exists some random  error in data.  This is true whether we are talking about neural activity, weather patterns or economics.  Nothing behaves exaclty as expected, instead there is always some random error.  I can formalize this error by adding an error term, $\epsilon$, to equation \@ref(eq:SupModApprox).  

\begin{equation}
  \mathbf{Y} = f(\mathbf{X}) + \epsilon
  (\#eq:SupMod)
\end{equation}

Where $\epsilon$ represents the inherent random error, is assumed to be indepedent and has an assumed mean of zero.  In this case independence means that the error is unaffected by the input variable (even though this is not always true).  Assuming a zero mean error implies that there is no inherent bias in the error, e.g., the error will not shift the data in one direction more than any others. The implication of $\epsilon$ is that even if we are able to perfectly estimate $f(\mathbf{X})$, we would be unable to predict $\mathbf{Y}$ with perfect accuracy due to the inherent error which is indepedent of, and so cannot be predicted by, $\mathbf{X}$.


However, the problem is that while we assume this relationship exists, we do not know what the function $f(\mathbf{X})$ is.  To that end, supervised models seek to estimate this function using data consisting of inputs values paied with corresponding output values.  When used to estimated the parameters of a model, this dataset if often referred to as **training data**.  This is in contrast to **test data**, which as the name states, is used to test the accuracy of the model on data different than what it was trained on.  Using the estimate of the function learned from the training data we are able to make predictions of the output values given the input values in the test data.

\begin{equation}
  \hat{\mathbf{Y}} = \hat{f}(\mathbf{X})
  (\#eq:SupModEst)
\end{equation}

Note that both the function and the output variable are indicated as estimates (through their tiny hats), but the input variable is not indicated as an estimate.  This is because we know what the true inputs are we just don't know what the function that relates the inputs to the outputs truly is and following from that we do not know what the output truly is for any given input, hence the tiny hats. 

The most common features which distinguish the different supervised models are as follows

- The mathematical structure of $f(\mathbf{X})$  
- The type of data that make up the output variable
- Estimation method of $f(\mathbf{X})$


## Assessing Model Quality of Fit

### MSE




** START FROM HERE**
However, note that unlike equation \@ref(eq:SupMod) When estimating the function $f()$, there are two types of errors to consider

<!-- ```{r, echo=FALSE, warning=FALSE} -->
<!-- library(NHANES) -->
<!-- NH_smp <- NHANES[sample(nrow(NHANES),500),] -->
<!-- Age <- NH_smp$Age -->
<!-- Height <- NH_smp$Height -->
<!-- fit <- lm((Height)~ Age) -->

<!-- fit.pred <- (predict(fit,data.frame(Age=min(Age):max(Age)))) -->
<!-- NH_2 <- tibble(Age=min(Age):max(Age),Height=fit.pred ) -->
<!-- NH_smp %>% ggplot(aes(Age,Height)) + geom_jitter() +geom_line(data=NH_2,aes(Age,Height)) -->
<!-- ``` -->






<!-- ```{r} -->
<!-- library(ElemStatLearn) -->
<!-- library(tidyverse) -->
<!-- mrk <- as_tibble(marketing) -->
<!-- mrk <- mrk %>% mutate(Inc = 10000 + (Income-1)*5000) -->
<!-- mrk$Inc[mrk$Income==6] <- 40000 -->
<!-- mrk$Inc[mrk$Income==7] <- 50000 -->
<!-- mrk$Inc[mrk$Income==8] <- 75000 -->
<!-- mrk$Inc[mrk$Income==9] <- 90000 -->
<!-- mrk %>% ggplot(aes(Edu,Income)) + geom_point() -->
<!-- ``` -->









```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```


